export class CountryID {

countryid: Map<string,string> = new Map([

["Afghanistan", "af"],
["Albania", "al"],
["Algeria", "dz"],
["Andorra", "ad"],
["Angola", "ao"],
["Antigua and Barbuda", "ag"],
["Argentina", "ar"],
["Armenia", "am"],
["Aruba", "aw"],
["Australia", "au"],
["Austria", "at"],
["Azerbaijan", "az"], 
["Bahamas", "bs"],
["Bahrain", "bh"],
["Bangladesh", "bd"],
["Barbados", "bb"],
["Belarus", "by"],
["Belgium", "be"],
["Belize", "bz"],
["Benin", "bj"],
["Bhutan", "bt"],
["Bolivia", "bo"],
["Bosnia and Herzegovina", "ba"],
["Botswana", "bw"],
["Brazil", "br"],
["Brunei", "bn"],
["Bulgaria", "bg"],
["Burkina [Faso", "bf"],
["Burundi", "bi"],
["Cambodia", "kh"],
["Cameroon", "cm"],
["Canada", "ca"],
["Cabo Verde", "cv"],
["Central African Republic", "cf"],
["Chad", "td"],
["Chile", "cl"],
["China", "cn"],
["Colombia", "co"],
["Comoros", "km"],
["Congo (Democratic Republic of the)", "cd"],
["Congo (Republic of the)", "cg"],
["Costa Rica", "cr"],
["Cote d'Ivoire", "ci"],
["Croatia", "hr"],
["Cuba", "cu"],
["Curacao", "cw"],
["Cyprus", "cy"],
["Czechia", "cz"],
["Denmark", "dk"],
["Djibouti", "dj"],
["Dominica", "dm"],
["Dominican Republic", "do"],
["Ecuador", "ec"],
["Egypt", "eg"],
["El Salvador", "sv"],
["Equatorial Guinea", "gq"],
["Eritrea", "er"],
["Estonia", "ee"],
["Ethiopia", "et"],
["Fiji", "fj"],
["Finland", "fi"],
["France", "fr"],
["Gabon", "ga"],
["Gambia", "gm"],
["Georgia", "ge"],
["Germany", "de"],
["Ghana", "gh"],
["Greece", "gr"],
["Grenada", "gd"],
["Guatemala", "gt"],
["Guinea", "gn"],
["Guinea-Bissau", "gw"],
["Guyana", "gy"],
["Haiti", "ht"],
["Holy See", "va"],
["Honduras", "hn"],
["Hong Kong", "hk"],
["Hungary", "hu"],
["Iceland", "is"],
["India", "in"],
["Indonesia", "id"],
["Iran", "ir"],
["Iraq", "iq"],
["Ireland", "ie"],
["Israel", "il"],
["Italy", "it"],
["Jamaica", "jm"],
["Japan", "jp"],
["Jordan", "jo"],
["Kazakhstan", "kz"],
["Kenya", "ke"],
["Kiribati", "ki"],
["Korea (North)", "kp"],
["Korea (South)", "kr"],
["Kosovo", "xk"],
["Kuwait", "kw"],
["Kyrgyzstan", "kg"],
["Laos", "la"],
["Latvia", "lv"],
["Lebanon", "lb"],
["Lesotho", "ls"],
["Liberia", "lr"],
["Libya", "ly"],
["Liechtenstein", "li"],
["Lithuania", "lt"],
["Luxembourg", "lu"],
["Macau", "mo"],
["Macedonia", "mk"],
["Madagascar", "mg"],
["Malawi", "mw"],
["Malaysia", "my"],
["Maldives", "mv"],
["Mali", "ml"],
["Malta", "mt"],
["Marshall Islands", "mh"],
["Mauritania", "mr"],
["Mauritius", "mu"],
["Mexico", "mx"],
["Micronesia", "fm"],
["Moldova", "md"],
["Monaco", "mc"],
["Mongolia", "mn"],
["Montenegro", "me"],
["Morocco", "ma"],
["Mozambique", "mz"],
["Myanmar", "mm"],
["Namibia", "na"],
["Nauru", "nr"],
["Nepal", "np"],
["Netherlands", "nl"],
["New Zealand", "nz"],
["Nicaragua", "ni"],
["Niger", "ne"],
["Nigeria", "ng"],
["Norway", "no"],
["Oman", "om"],
["Pakistan", "pk"],
["Palau", "pw"],
["Palestinian Territories", "ps"],
["Panama", "pa"],
["Papua New Guinea", "pg"],
["Paraguay", "py"],
["Peru", "pe"],
["Philippines", "ph"],
["Poland", "pl"],
["Portugal", "pt"],
["Qatar", "qa"],
["Romania", "ro"],
["Russia", "ru"],
["Rwanda", "rw"],
["Saint Kitts and Nevis", "kn"],
["Saint Lucia", "lc"],
["Saint Vincent and the Grenadines", "vc"],
["Samoa", "ws"],
["San Marino", "sm"],
["Sao Tome and Principe", "st"],
["Saudi Arabia", "sa"],
["Senegal", "sn"],
["Serbia", "rs"],
["Seychelles", "sc"],
["Sierra Leone", "sl"],
["Singapore", "sg"],
["Sint Maarten", "sx"],
["Slovakia", "sk"],
["Slovenia", "si"],
["Solomon Islands", "sb"],
["Somalia", "so"],
["South Africa", "za"],
["South Sudan", "ss"],
["Spain", "es"],
["Sri Lanka", "lk"],
["Sudan", "sd"],
["Suriname", "sr"],
["Swaziland", "sz"],
["Sweden", "se"],
["Switzerland", "ch"],
["Syria", "sy"],
["Taiwan", "tw"],
["Tajikistan", "tj"],
["Tanzania", "tz"],
["Thailand", "th"],
["Timor-Leste", "tl"],
["Togo", "tg"],
["Tonga", "to"],
["Trinidad and Tobago", "tt"],
["Tunisia", "tn"],
["Turkey", "tr"],
["Turkmenistan", "tm"],
["Tuvalu", "tv"],
["Uganda", "ug"],
["Ukraine", "ua"],
["United Arab Emirates", "ae"],
["United Kingdom", "gb"],
["United States", "us"],
["Uruguay", "uy"],
["Uzbekistan", "uz"],
["Vanuatu", "vu"],
["Venezuela", "ve"],
["Vietnam", "vn"],
["Yemen", "ye"],
["Zambia", "zm"],
["Zimbabwe", "zw"]
]);


}